### ISSUE TITLE
rowGrid is not getting heights correct

### ISSUE THREAD

**Issue by jdkealy** [brunjo/rowGrid#5]
Hi, 
rowGrid seems to be making the height of the item-selector smaller than the image it is resizing. I'm calling rowGrid after all my images load and I'm only setting the height of the image, hoping rowGrid can calculate the widths automatically for me. So far so good except this one issue. 

<img width="1422" alt="screen shot 2016-09-26 at 3 41 54 pm" src="https://cloud.githubusercontent.com/assets/386993/18849193/d7fee7bc-83ff-11e6-92a7-13c31421ca99.png">

**Comment by brunjo** [comment]
Did you added the CSS from the example? (https://github.com/brunjo/rowGrid/blob/master/example/index.html)

In particular, this part:

``` CSS
.item img {
  max-width: 100%;
  max-height: 100%;
}
```

**Comment by jdkealy** [comment]
Thanks sorry I missed that.
