### ISSUE TITLE
finished callback?

### ISSUE THREAD

**Issue by jdkealy** [brunjo/rowGrid#6]
I'm using react and would like to cover the grid with a mask while it's doing its business and then remove it when it's done. I would ordinarily do this with a callback function. Is there any "finished" event or optional callback?

**Comment by brunjo** [comment]
There is no callback but the `rowGrid()` method is a synchronous method. So you can just do something like this:

``` JS
rowGrid(container, options);
// now everything looks great
hideOverlay();
```

**Comment by jdkealy** [comment]
cool thanks!
