### ISSUE TITLE
Bildgröße "0" bei rowGrid(container, 'appended');

### ISSUE THREAD

**Issue by B0rner** [brunjo/rowGrid#7]
Hallo,

zunächst: danke für die rowGrid Bibliothek. Sie erleichtert das Anordnen der Bilder erheblich.

Dazu folgende Frage: die Bilder müssen alle eine gleiche Höhe haben, eine Breiten- oder Höhenangabe als HTML Attribut ist allerdings nicht notwendig.
Das funktioniert so super.

Wenn ich allerdings Bilder dynamisch hinzufüge (mit der gleichen Höhe wie bereits vorhandene Bilder) und nach dem Abschluss der DOM Änderung `rowGrid(container, 'appended');` aufrufe, erhalten alle neuen Bilder im Image Tag und im umschließenden div die Höhe=0 und die Breite=0.

Muss man den, für endless scrolling oder dem dynmaischen Hinzufügen zwingend HTML Attribute für Höhe und Breite mit angeben? Das würde die Dynamik beim Einsatz eingrenzen.

Danke und viele Grüße,
B0rner

**Comment by brunjo** [comment]
Wenn du keine `width` und `height` Attribute zu den `img` Tags hinzufügst, darfst du `rowGrid(container, 'appended');` erst aufrufen, wenn alle neu hinzugefügten Bilder geladen sind damit die Breite der einzelnen Bilder ausgelesen werden kann. Ansonsten ist es nicht möglich die neue Breite der Bilder zu berechnen.

**Comment by B0rner** [comment]
hey,

das ich `rowGrid(container, 'appended');` erst nach dem "reinbauen" der Bilder ausführen darf, habe ich verstanden und auch so umgesetzt. Aber es klappt trotzdem nicht:

Die Bilder werden per $.post geladen und dann in einer `$.each`-Schleife in das DOM gebaut. Ohne Angabe einer Höhe. Dazu greife ich mir aus dem DOM einen Platzhalter, den ich mit den Daten (BildUrl) aus dem Ajax Call befülle.
Anschließend führe ich `rowGrid(container, 'appended');` aus. Hier bekommen die Bilder alle ein `width` und `height` Attribut, welches aber auf 0 gesetzt wird. Also: rowGrid findet die div's/img's, aber setzt die Maße auf 0.
Selbst dann, wenn ich die Ausführung von  `rowGrid(container, 'appended');`  in ein Timeout mit 4000ms setze.
```

 $.each(data, function (key, value)
                {
                ph=$('#pictureResultPh').clone().appendTo('.rowGridContainer'); //Platzhalter greifen
                ph.removeAttr('id');  //in der Kopie des Platzhalters die ID entfernen
                ph.children('img').attr('src','http://localhost:81/fotos/s'+value.originalBild); //aus den geladenen Daten die BildURL nehmen und einsetzen                 
                });
                 
               setTimeout(rowGrid(myObj.getRowGridContainer(), 'appended'),4000);  //alle Bilder eingebaut? Dann rowGrid starten
```

Wenn ich in der gleichen Session ein weiteres Mal den Ajax Request aufrufe, werden die Bilder des 1. Request ordentlich angezeigt.
Vielleicht in Timeing-Problem?

**Comment by B0rner** [comment]
...Nachtrag:
Ich habe die Passage jetzt vereinfacht, so dass von der API nicht nur ein Array mit neuen Bildern kommt, sondern der gesamte HTML Quellcode für die einzelnen Items. 
Jetzt funktioniert das `' appended' `, wenn man den Neuaufbau in ein timeout mit ein paar Millisekunden Verzögerung setzt, in dem Fall mit der jQuery Version:

```
 $('.rowGridContainer').append(data);
 setTimeout(  function() { $('.rowGridContainer').rowGrid('appended'); }  ,200);
```
Das ganze ist nur äußerst unelegant, da man ja nie weiß, welchen Zeitraum man wirklich warten muss. 
Etwas debugging beim rowGrid Quellcode bringt mich zur Erkenntnis, dass rowGrid durchaus die nachgeladenen Items findet.
`var items = $lastRow.nextAll(options.itemSelector).add($lastRow);  `
funktioniert. Trotzdem wird die Höhe/Breite der Bilder durch rowGrid auf 0 gesetzt.
Frage 1:  Kann es sein, dass die Items zwar im DOM sind, aber der Brwoser noch nicht die Bilder geladen hat? 

Ich möchte an dieser Stelle gerne noch eine Frage anhängen. Für das Szenario, dass ich keine Items anhänge, sondern den Inhalt von `.rowGridContainer ` komplett mit neuen, per Ajax erhaltenen Daten ersetzeFrage 2: Kann ich danach durch rowGrid das Layout gerade ziehen lassen?

Ein einfaches ausführen von `$('.rowGridContainer').rowGrid();` hat zur Folge, dass die Default-Optionen geladen werden, während der `appended`  Zweig mit den richtigen rowGrid Optionen arbeitet, die ich einst beim Laden der Seite angelegt habe.

Vielen Dank schonmal...

**Comment by brunjo** [comment]
Hi B0rner,

1) Funktioniert es jetzt mit einem Timeout, der auf ein paar Sekunden gesetzt wird? Dann wird es daran liegen, dass zwar die Bilder im DOM hinzugefügt wurden, aber noch nicht geladen sind. Man kann mit dem `onload` Event auch darauf warten, dass die Bilder vollständig heruntergeladen sind und erst dann die `rowGrid` Methode aufrufen. Siehe dazu hier den StackOverflow Beitrag: https://stackoverflow.com/a/6488123/1890035

2) Beim [rowGrid jQuery Plugin](https://github.com/brunjo/rowGrid.js/) werden bei erneutem Aufruf der `rowGrid` Methode die Default-Optionen verwendet. Du musst die Optionen also erneut als Parameter übergeben. 
Beim [reinen JavaScript Plugin von rowGrid](https://github.com/brunjo/rowGrid/) werden hingegen die vorher übergebenen Optionen genutzt. Das Verhalten des jQuery Plugins kann gerne geändert werden. Ich würde einen entsprechenden Pull-Request mergen.

**Comment by B0rner** [comment]
Hey Brunjo,

zu 1.) das mit dem Timeout funktioniert so "halb". Ich muss die Wartezeit recht hoch setzen, um sicher zu gehen, dass alle Bilder bei allen User-Szenarien auch geladen sind. Das mag im LAN funktionieren, aber nicht im Produktivbetrieb, wenn jemand bspw. mit EDGE die Seite aufruft. Tatsächlich hatte ich die Variante mit dem `load()` zwischenzeitlich auch schon ergoogelt.

Ich lade die Bilder am Block, was zur Folge hat, dass ich für jedes Bild das load-Event anhänge, da man ja nichtsagen kann, welches Bild als letztes geladen ist. Das sieht dann so aus:
```
$('.rowGridContainer img').load(
                        function () {
                            $('.rowGridContainer').rowGrid(myObj.getRowGridOptions);
                        });
```
Das hat zur Folge, dass bei jedem Schub (20-100 Bilder) auch bis zu 100 Events belauscht werden und 100x rowGrid neu aufgerufen wird. Wenig elegant. Auch das Bauen von Hilfskonstrukten, in denen man versucht, trotz der 100 Events ggf. nur beim letzten mal rowGrid zu starten, erscheint mir nicht sonderlich elegant. Hast du da eine Idee?


2.) Das ist natürlich etwas irritierend, dass sich die jQuery und die Vanilla Version unterschiedlich verhalten.
Ich habe das bei Git mit dem PR noch nicht gemacht. Vielleicht schaue ich mir das mal an.

Gruß,
B0rner

**Comment by B0rner** [comment]
Hi brunjo,
die Variante mit dem Timeout habe ich wieder zurück gebaut, denn es ist nicht absehbar. Meine webseite wird über das schnelle LAN, als auch über WAN (auch mobil) abgerufen. Die Ladezeiten, bis alles vollständig da ist, sind zu unterschiedlich, um einen passenden Timeoutwert zu ermitteln.
In der 200ms Version oben funktioniert es nur, wenn wirkich binnen 200ms alle Bilder da sind.
Die onload Variante (es gibt diverse abwandlungen) habe ich in verschiedenen Aspekten ausprobiert.
Ich habe nun die Version von deinem verlinkten SO Artikel übernommen. Richtig robust ist das aber nicht.
...wobei mein Chrome unter Windows für das Problem weniger bis nicht anfällig ist und der Firefox (unter Linux) dauernt in ein Problem rennt. :-/

Hast du noch eine Idee zum Thema?

**Comment by brunjo** [comment]
Hi B0rner,
Die paar hundert Events auf die gehört wird, sollten eigentlich kein Problem sein. Aber die rowGrid Methode sollte nicht bei jedem auslösen eines Events aufgerufen werden, da diese Methode relativ aufwendig ist. Die Methode sollte wenn möglich nur nachdem alle Fotos geladen sind aufgerufen werden.
